# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae50d394a2116069f75e53e8b25bed00e3317dbd1dbab4b6fa60a3d0f9fd3c024122246bf90b72ec4cf5bdcac0fab15c78ca423622d0a6489db6093842e7dfa4

test:
  secret_key_base: 2452c78ccd57a5d26808a609520d35f68e862a8196e27bfcc0bbaec1aaea01436091cae94a00c2d4d1b5334b06e8cf3678bcd78edd78bb0e8e7e198b01939f5d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
